#!/bin/bash

dnsmachine="cs5700cdnproject.ccs.neu.edu"
ec2machines="ec2-54-85-32-37.compute-1.amazonaws.com
ec2-54-193-70-31.us-west-1.compute.amazonaws.com
ec2-52-38-67-246.us-west-2.compute.amazonaws.com
ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
ec2-54-233-185-94.sa-east-1.compute.amazonaws.com"

# keyfile="/Users/kevin/.ssh/id_rsa"
# username="abraham"

while [ $# -gt 0 ]
do
	case $1 in
		-p)
		shift; port=$1;;
		-o)
		shift; origin=$1;;
		-n)
		shift; name=$1;;
		-u)
		shift; username=$1;;
		-i)
		shift; keyfile=$1;;
		*)
		echo "Please use the following format ./[deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"; exit 0;;
	esac
	shift
done

if [ ! "$port" ] || [ ! "$origin" ] || [ ! "$name" ] || [ ! "$username" ] || [ ! "$keyfile" ]; then
	echo "Please use the following format ./[deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>";
	exit 0;
fi

if [ "$port" -lt 40000 ] || [ "$port" -gt 65535 ];then
	echo "Please enter a port between 40000 and 65535";
	exit 0;
fi


ssh -i $keyfile $username@$dnsmachine "nohup ./dnsserver -p $port -n $name >> /dev/null 2>&1 &"

for machine in $ec2machines
do
	ssh -i $keyfile $username@$machine "nohup ./httpserver -p $port -o $origin >> /dev/null 2>&1 &"
done